### ISSUE TITLE
Make error message for rmdir better

### ISSUE THREAD

**Issue by yruen** [yruen/Texture-Filterer#35]
https://github.com/yruen/Texture-Filterer/blob/d1ef041b52d2bebd568c917a1abe1d7dff5af6b6/other_scripts/otherUtils.py#L38

**Comment by nikhilnarla** [comment]
Hi @yruen , Are you looking for something like this?

try:
    error = os.rmdir(dir)
except:
    print("An exception has occurred while trying to delete the directory : " ,dir)
    print("Exception class : ", sys.exc_info()[0])
    print("Exception message : ", sys.exc_info()[1])

**Comment by yruen** [comment]
@nikhilnarla thank you for your suggestion,

I was thinking more of it catching the error if it detects there are still files in the folder that way it'd print out something like "Could not delete: folder is not empty" but thank you

**Comment by yruen** [comment]
@nikhilnarla that's a very valid point. I did not consider that. Thank you for your comment, I'll use this as a base
